name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node and Yarn
        uses: actions/setup-node@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.REGION }}

      - name: Build the app
        run: yarn build

      - name: Deploy the app
        run: yarn deploy
